version: '3'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8080:8080"
    depends_on:
      - mysql-user
    image: peterhenskens/user-service
    links:
      - mysql-user
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-user
      MYSQL_DB_PORT: 3306

  experience-service:
    build:
      context: ./experience-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo-experience
    image: peterhenskens/experience-service
    links:
      - mongo-experience
    environment:
      MONGO_HOST: mongo-experience
      MONGO_PORT: 27017

  api-gateway:
    build:
      context: ./api-gateway
    depends_on:
      - user-service
      - experience-service
    image: peterhenskens/api-gateway
    ports:
      - "8083:8083"
    links:
      - user-service
      - henskens-service
    environment:
      USER_SERVICE_BASEURL: user-service:8080
      EXPERIENCE_SERVICE_BASEURL: experience-service:8081

  mysql-user:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - user-data:/var/lib/mysql

  mongo-experience:
    image: mongo:latest
    command: ["mongod", "--setParameter", "enableLocalhostAuthBypass=0"]
    ports:
      - "27017:27017"
    volumes:
      - experience-data:/data/db

volumes:
  user-data:
  experience-data:
