version: '3'

services:
  db1:
    image: couchbase
    container_name: db1
    hostname: db1
    networks:
      - couchbase-net
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    environment:
      - SERVICES=data;index;query;fts
      - CB_REST_USERNAME=Administrator
      - CB_REST_PASSWORD=g9VNheVwrF@!3wS

networks:
  couchbase-net:
